---
baseURL: https://review.aicurious.io/
title: Short Review ML
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/vietanhdev/review.aicurious.io
  geekdocEditPath: edit/master/content

  geekdocSearch: true
  geekdocSearchShowParent: true